#!/usr/bin/env bash

D=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT=$( cd -- "$D/../.." &> /dev/null && pwd )

if [ "$1" == "--build" ]; then
    shift
    pushd $ROOT
    rebar3 as metrics escriptize || exit 1
    popd
fi

$ROOT/_build/metrics/bin/etylizer "$@"
