#!/bin/bash
set -e

"$(dirname "$0")/ety_metrics" \
    -P . \
    -S ./test_files/tycheck_simple \
    -I ./include \
    -I ./src \
    -I ./erlang_types \
    -I ./erlang_types/dnf \
    --type-overlay overlays/etylizer_overlay.erl \
    -f \
    --report-mode report --report-timeout 4000 \
    --metrics-file typecheck_test_metrics.json \
    --no-deps \
    "$@"
