#!/usr/bin/env bash

D=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ "$1" == "--build" ]; then
    shift
    pushd $D
    make build || exit 1
    popd
fi

$D/_build/prod/bin/etylizer "$@"
