#!/usr/bin/env bash

D=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ "$1" == "--build" ]; then
    shift
    pushd "$D" > /dev/null
    (make build > /dev/null) || exit 1
    popd > /dev/null
fi

$D/_build/default/bin/etylizer "$@"
