#!/bin/bash
set -e

./ety_metrics \
    -P . \
    -S ./src \
    -I ./include \
    -I ./src \
    -I ./src/erlang_types \
    -I ./src/erlang_types/dnf \
    --type-overlay overlays/etylizer_overlay.erl \
    -f \
    --report-mode report --report-timeout 1000 \
    --metrics-file etylizer_metrics.json \
    --no-deps \
    "$@"
