#!/bin/bash
set -e

# metrics_skip/etylizer.txt is a list of `-i module:name/arity` lines for
# functions that don't complete within --report-timeout below.
./ety_metrics \
    -P . \
    -S ./src \
    -I ./include \
    -I ./src \
    -I ./src/erlang_types \
    -I ./src/erlang_types/dnf \
    --type-overlay overlays/etylizer_overlay.erl \
    -f \
    --report-mode report --report-timeout 45000 \
    --metrics-file etylizer_metrics.json \
    --no-deps \
    $(cat metrics_skip/etylizer.txt) \
    "$@"
